// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Durable policy governing how a spawned child's terminal result reaches its
 * parent.
 */
export type CompletionDeliveryPolicy = { "kind": "tool_result_only" } | { "kind": "notify_parent", trigger_turn: boolean, } | { "kind": "legacy" };
