// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Harness behavior used for prompts, developer instructions, and tool schemas.
 */
export type HarnessMode = "codex" | "claudecode" | "seed" | "auto";
