// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A UTF-8 path for preserving raw path compatibility at the app-server API
 * boundary while Codex migrates to [`PathUri`].
 *
 * Supports storing arbitrary strings read from the API and converting to and
 * from [`PathUri`] using an explicitly selected native path convention.
 *
 * When converting from [`PathUri`], "native" refers to the supplied
 * [`PathConvention`], which may be foreign to the operating system running
 * this process. Non-UTF-8 paths are converted lossily for JSON compatibility.
 * Deserialization and compatibility redaction preserve raw text; path-producing
 * code should use the typed conversions. Relative text remains valid until an
 * operation such as [Self::to_path_uri] requires an absolute path.
 */
export type LegacyAppPathString = string;
