// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelInternalUsageStatus } from "./ModelInternalUsageStatus";
import type { ModelLoadStatus } from "./ModelLoadStatus";
import type { ModelVariantMetadata } from "./ModelVariantMetadata";

/**
 * TRAE backend business metadata that should travel with model entries.
 *
 * Keep this separate from generic model capabilities so quota/security policy
 * UI can evolve without coupling to upstream model semantics.
 */
export type ModelBusinessMetadata = {
/**
 * Whether the TRAE backend marked this model as the catalog default.
 */
backend_is_default: boolean,
/**
 * Trae enterprise model config source: 1=system, 2=tenant built-in, 3=user custom.
 */
config_source: number | null,
/**
 * Provider identifier for Trae enterprise custom models.
 */
provider: string | null,
/**
 * Whether the model is blocked for L4 repositories by the TRAE backend.
 */
is_l4_repo_restricted: boolean,
/**
 * Whether the model consumes the internal weekly usage quota.
 */
is_internal_usage_limit: boolean,
/**
 * Latest weekly usage snapshot, when the TRAE usage endpoint is available.
 */
internal_usage: ModelInternalUsageStatus | null,
/**
 * Best-effort model load snapshot from the TRAE queue service.
 */
load: ModelLoadStatus | null,
/**
 * TRAE backend model variants available for this display model.
 */
variants: ModelVariantMetadata, };
