// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelTokenLimits } from "./ModelTokenLimits";
import type { ReasoningEffortPreset } from "./ReasoningEffortPreset";

export type ModelVariantMetadata = {
/**
 * Default `__dev` backend model name.
 */
standard_key: string | null,
/**
 * Context window for the default `__dev` backend model.
 */
standard_context_window: bigint | null,
/**
 * Default reasoning effort for the default `__dev` backend model.
 */
standard_default_reasoning_level?: import("./ReasoningEffort").ReasoningEffort,
/**
 * Supported reasoning efforts for the default `__dev` backend model.
 */
standard_supported_reasoning_levels?: Array<ReasoningEffortPreset>,
/**
 * Optional `__max` backend model name.
 */
max_key: string | null,
/**
 * Context window for the optional `__max` backend model.
 */
max_context_window: bigint | null,
/**
 * Default reasoning effort for the optional `__max` backend model.
 */
max_default_reasoning_level?: import("./ReasoningEffort").ReasoningEffort,
/**
 * Supported reasoning efforts for the optional `__max` backend model.
 */
max_supported_reasoning_levels?: Array<ReasoningEffortPreset>,
/**
 * Percentage of the max context window used as the runtime effective window.
 */
effective_context_window_percent: bigint | null,
/**
 * Raw per-backend ceilings, before display caps or client safety headroom.
 */
backend_token_limits?: { [key in string]?: ModelTokenLimits }, };
