// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelInternalUsageStatus = {
/**
 * Percentage of the weekly basic quota already consumed, clamped to 0..=100.
 */
usage_percent: number,
/**
 * Remaining weekly basic quota, rounded for display when the backend provides it.
 */
quota_remaining: number | null,
/**
 * Total weekly basic quota, rounded for display when the backend provides it.
 */
quota_limit: number | null,
/**
 * Whether the quota is exhausted.
 */
is_depleted: boolean,
/**
 * Backend reset/end time, if provided.
 */
reset_time: bigint | null, };
