// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModelLoadStatus = {
/**
 * Percentage of current model load.
 */
load_percent: number,
/**
 * Model queue size when the backend provides it.
 */
queue_size: bigint | null,
/**
 * Current outgoing QPM reported by the backend.
 */
out_qpm: bigint | null,
/**
 * Total QPM capacity reported by the backend.
 */
total_qpm: bigint | null, };
