// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classification of a model into a known family/series.
 *
 * Used to select per-family base instructions and for slug normalization.
 * Defaults to `Generic` when the family cannot be determined.
 */
export type ModelFamily = "gpt" | "claude" | "deepseek" | "gemini" | "doubao" | "seed" | "generic";
