// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPath } from "./AgentPath";
import type { CompletionDeliveryPolicy } from "./CompletionDeliveryPolicy";
import type { ThreadId } from "./ThreadId";

export type SubAgentSource = "review" | "compact" | { "thread_spawn": { parent_thread_id: ThreadId, depth: number, agent_path: AgentPath | null, agent_nickname: string | null, agent_role: string | null, completion_delivery_policy: CompletionDeliveryPolicy, } } | "memory_consolidation" | { "workflow": { owner_thread_id: ThreadId, run_id: string, node_id: string, attempt: number, } } | { "other": string };
