// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParsedCommand } from "../ParsedCommand";
import type { JsonValue } from "../serde_json/JsonValue";

/**
 * Distinguishes actual builtin arguments from a shell command parsed as a readonly action.
 */
export type CommandActionInput = { "type": "builtin", name: string, arguments: JsonValue, } | { "type": "shell", command: Array<string>, parsedCmd: Array<ParsedCommand>, };
