// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";
import type { CommandActionInput } from "./CommandActionInput";

export type CommandAction = { "type": "read", command: string, name: string, path: LegacyAppPathString,
/**
 * Original readonly input; absent in older items.
 */
input: CommandActionInput | null, } | { "type": "listFiles", command: string, path: string | null,
/**
 * Original readonly input; absent in older items.
 */
input: CommandActionInput | null, } | { "type": "search", command: string, query: string | null, path: string | null,
/**
 * Original readonly input; absent in older items.
 */
input: CommandActionInput | null, } | { "type": "unknown", command: string,
/**
 * Name from the actual Skill tool invocation; null for shell commands.
 */
skillName: string | null, };
