// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FallbackSettingAdjustmentReason } from "./FallbackSettingAdjustmentReason";
import type { FallbackSettingField } from "./FallbackSettingField";
import type { FallbackTarget } from "./FallbackTarget";

export type FallbackSettingsAdjustedEvent = { target: FallbackTarget, field: FallbackSettingField, requested: string | null, effective: string | null, reason: FallbackSettingAdjustmentReason, };
