// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FallbackSettingsSnapshot } from "./FallbackSettingsSnapshot";
import type { FallbackTarget } from "./FallbackTarget";
import type { FallbackTrigger } from "./FallbackTrigger";

export type FallbackCommittedEvent = { ordinal: number, configuredPrimary: FallbackTarget, target: FallbackTarget, trigger: FallbackTrigger, attemptCount: number, settings: FallbackSettingsSnapshot, };
