// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FallbackCandidateSkipReason } from "./FallbackCandidateSkipReason";
import type { FallbackTarget } from "./FallbackTarget";

export type FallbackCandidateSkippedEvent = { ordinal: number, target: FallbackTarget, reason: FallbackCandidateSkipReason, };
