// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FallbackSettingSnapshot } from "./FallbackSettingSnapshot";

export type FallbackSettingsSnapshot = { reasoningEffort: FallbackSettingSnapshot, reasoningSummary: FallbackSettingSnapshot, verbosity: FallbackSettingSnapshot, serviceTier: FallbackSettingSnapshot, personality: FallbackSettingSnapshot, };
