// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FallbackErrorKind } from "./FallbackErrorKind";

export type FallbackExhaustedEvent = { attempts: number, finalErrorKind: FallbackErrorKind, };
