// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSystemAccessMode } from "./FileSystemAccessMode";
import type { FileSystemPath } from "./FileSystemPath";
import type { FileSystemSandboxEntryMissingPathBehavior } from "./FileSystemSandboxEntryMissingPathBehavior";

export type FileSystemSandboxEntry = { path: FileSystemPath, access: FileSystemAccessMode,
/**
 * Preserve optional-path behavior across runtime permission overrides.
 */
missingPathBehavior: FileSystemSandboxEntryMissingPathBehavior | null, };
