// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification emitted when model loop detection triggers compact-and-retry recovery.
 */
export type LoopDetectedRecoveringNotification = { threadId: string, turnId: string, reason: string, attempt: number, maxAttempts: number, };
