// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeChangeDecision } from "./ModeChangeDecision";

/**
 * Notification emitted when a mode change request reaches a terminal decision.
 */
export type ModeChangeResolvedNotification = { threadId: string, turnId: string, requestId: string,
/**
 * The target mode: "plan" or "default".
 */
targetMode: string, decision: ModeChangeDecision, };
