// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModeChangeAllowedPrompt } from "./ModeChangeAllowedPrompt";

/**
 * Notification emitted when the model requests a collaboration mode change.
 */
export type ModeChangeRequestedNotification = { threadId: string, turnId: string,
/**
 * Stable ID for replying to this request.
 */
requestId: string,
/**
 * The target mode: "plan" or "default".
 */
targetMode: string,
/**
 * Tool call ID that triggered the mode change, when available.
 */
sourceToolCallId: string | null,
/**
 * Human-readable reason for the mode change request.
 */
reason: string,
/**
 * Bash command semantic prompts to pre-approve (exit plan mode only).
 */
allowedPrompts?: Array<ModeChangeAllowedPrompt>, };
