// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FallbackAttemptFailedEvent } from "./FallbackAttemptFailedEvent";
import type { FallbackAttemptStartedEvent } from "./FallbackAttemptStartedEvent";
import type { FallbackCandidateSkippedEvent } from "./FallbackCandidateSkippedEvent";
import type { FallbackCommittedEvent } from "./FallbackCommittedEvent";
import type { FallbackExhaustedEvent } from "./FallbackExhaustedEvent";
import type { FallbackSettingsAdjustedEvent } from "./FallbackSettingsAdjustedEvent";

export type ModelFallbackEvent = { "type": "attemptStarted" } & FallbackAttemptStartedEvent | { "type": "candidateSkipped" } & FallbackCandidateSkippedEvent | { "type": "settingsAdjusted" } & FallbackSettingsAdjustedEvent | { "type": "attemptFailed" } & FallbackAttemptFailedEvent | { "type": "committed" } & FallbackCommittedEvent | { "type": "exhausted" } & FallbackExhaustedEvent;
