// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessMode } from "../HarnessMode";
import type { InputModality } from "../InputModality";
import type { ModelBusinessMetadata } from "../ModelBusinessMetadata";
import type { ModelFamily } from "../ModelFamily";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ModelAvailabilityNux } from "./ModelAvailabilityNux";
import type { ModelServiceTier } from "./ModelServiceTier";
import type { ModelUpgradeInfo } from "./ModelUpgradeInfo";
import type { MultiAgentVersion } from "./MultiAgentVersion";
import type { ReasoningEffortOption } from "./ReasoningEffortOption";

export type Model = { id: string, model: string, configName: string | null, harnessMode: HarnessMode,
/**
 * Deprecated: use `harnessMode` instead. Kept for v2 clients that still read `modelFamily`.
 */
modelFamily: ModelFamily, upgrade: string | null, upgradeInfo: ModelUpgradeInfo | null, availabilityNux: ModelAvailabilityNux | null, displayName: string, description: string, hidden: boolean,
/**
 * Full model context window advertised by the provider.
 */
contextWindow: bigint | null,
/**
 * Maximum context window allowed for config overrides.
 */
maxContextWindow: bigint | null,
/**
 * Token threshold for automatic compaction declared by the model catalog.
 */
autoCompactTokenLimit: bigint | null, supportedReasoningEfforts: Array<ReasoningEffortOption>, defaultReasoningEffort: ReasoningEffort, inputModalities: Array<InputModality>,
/**
 * Provider id that should be selected together with this model.
 */
modelProviderId: string | null, supportsPersonality: boolean,
/**
 * Multi-agent runtime declared by this model, when available.
 */
multiAgentVersion: MultiAgentVersion | null,
/**
 * Deprecated: use `serviceTiers` instead.
 */
additionalSpeedTiers: Array<string>, serviceTiers: Array<ModelServiceTier>,
/**
 * Catalog default service tier id for upstream client compatibility.
 */
defaultServiceTier: string | null,
/**
 * TRAE business metadata used by fork-specific UI and routing policy.
 */
businessMetadata: ModelBusinessMetadata, isDefault: boolean, };
