// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueueOperation } from "./QueueOperation";

/**
 * Notification forwarded from app-server to frontend when the request is queued.
 */
export type QueueStatusNotification = { threadId: string, turnId: string,
/**
 * "queued" | "waiting" | "ready"
 */
state: string,
/**
 * Operation waiting for capacity. Null for ordinary sampling requests.
 */
operation: QueueOperation | null,
/**
 * Queue position, if available.
 */
position: number | null,
/**
 * Optional message from the backend.
 */
message: string | null, };
