// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Notification emitted when a session recap summary is generated.
 */
export type RecapGeneratedNotification = { threadId: string, turnId: string,
/**
 * The recap summary text.
 */
text: string, };
