// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionCallOutputBody } from "../FunctionCallOutputBody";

/**
 * Original Skill arguments and legacy display output: success summary or full failure.
 * Identity is still supplied by `CommandAction::Unknown::skill_name`.
 */
export type SkillInvocation = { arguments: string, output: FunctionCallOutputBody | null, success: boolean | null, };
