// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Signals that automatic approval must continue with core's synchronous
 * Guardian review rather than using an asynchronous fast approval.
 */
export type StrictReviewRequiredNotification = {
/**
 * Thread whose approval review requires the synchronous path.
 */
threadId: string,
/**
 * Turn that initiated the approval review.
 */
turnId: string,
/**
 * Stable identifier for the exact item or tool call requiring synchronous review.
 */
targetItemId: string,
/**
 * Unix timestamp in seconds when that review began.
 */
startedAt: number, };
