// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ThreadWorktreeSessionInfo } from "./ThreadWorktreeSessionInfo";

export type ThreadWorktreeSessionExitedNotification = { threadId: string, worktree: ThreadWorktreeSessionInfo, cwd: string, removed: boolean, };
