// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ThreadInboxStatusUpdatedNotification = { threadId: string, listening: boolean, fileCount: number,
/**
 * Names of the files currently being watched in the inbox directory.
 */
fileNames?: Array<string>,
/**
 * Recent output lines read from watched inbox files.
 */
outputLines?: Array<string>, };
