// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AbsolutePathBuf } from "../AbsolutePathBuf";
import type { CollaborationMode } from "../CollaborationMode";
import type { Personality } from "../Personality";
import type { ReasoningEffort } from "../ReasoningEffort";
import type { ReasoningSummary } from "../ReasoningSummary";
import type { Verbosity } from "../Verbosity";
import type { WindowsSandboxLevel } from "../WindowsSandboxLevel";
import type { ActivePermissionProfile } from "./ActivePermissionProfile";
import type { ApprovalsReviewer } from "./ApprovalsReviewer";
import type { AskForApproval } from "./AskForApproval";
import type { PermissionProfile } from "./PermissionProfile";
import type { SandboxPolicy } from "./SandboxPolicy";

export type ThreadSettings = {cwd: AbsolutePathBuf, runtimeWorkspaceRoots?: Array<AbsolutePathBuf>, approvalPolicy: AskForApproval, approvalsReviewer: ApprovalsReviewer, sandboxPolicy: SandboxPolicy, activePermissionProfile: ActivePermissionProfile | null, windowsSandboxLevel: WindowsSandboxLevel, model: string, modelProvider: string, modelBackendVariant: string | null, serviceTier: string | null, effort: ReasoningEffort | null, summary: ReasoningSummary | null, modelVerbosity: Verbosity | null, collaborationMode: CollaborationMode, personality: Personality | null};
