// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "../serde_json/JsonValue";
import type { TurnPlanStepStatus } from "./TurnPlanStepStatus";

export type TurnPlanStep = { step: string, status: TurnPlanStepStatus, activeForm?: string | null, taskId?: string | null, description?: string | null, owner?: string | null, blocks?: Array<string>, blockedBy?: Array<string>, metadata?: JsonValue | null, };
