// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowDefinitionOrigin } from "./WorkflowDefinitionOrigin";

export type WorkflowDefinitionUpdatedNotification = { threadId: string, definitionId: string, name: string, origin: WorkflowDefinitionOrigin, version: bigint, };
