// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowRunStatus } from "./WorkflowRunStatus";

/**
 * Low-latency hint that durable workflow state advanced. Clients must call
 * `workflow/events` with their last `afterSeq` to recover any notification gap.
 */
export type WorkflowUpdatedNotification = { threadId: string, runId: string, status: WorkflowRunStatus, nextEventSeq: bigint, };
