import { chromium } from 'playwright';
import { readFile, mkdir } from 'node:fs/promises';
import assert from 'node:assert/strict';
const browser = await chromium.launch({ ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : process.platform === 'darwin' ? { executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' } : {}), headless: true });
try {
 const page=await browser.newPage({viewport:{width:380,height:800}});
 const css=await readFile('dist/chat.css','utf8');
 await page.setContent(`<style>:root{--vscode-foreground:#ccc;--vscode-sideBar-background:#181818;--vscode-font-family:Arial;--vscode-font-size:13px;--vscode-descriptionForeground:#999;--vscode-panel-border:#333;--vscode-editorWidget-background:#252526;--vscode-input-background:#252526;--vscode-input-foreground:#ccc;--vscode-button-background:#0078d4;--vscode-button-foreground:#fff;--vscode-badge-background:#333;--vscode-badge-foreground:#ccc;--vscode-editor-font-family:monospace;--vscode-focusBorder:#0078d4;--vscode-textCodeBlock-background:#222;--vscode-button-secondaryBackground:#333;--vscode-button-secondaryForeground:#ccc;--vscode-errorForeground:#f88}${css}</style><header><div class="header-leading"><button id="back" aria-label="返回会话列表">←</button><span>TRAE</span></div><nav><button id="reconnect">重连</button><button id="review">变更</button><button id="history">历史</button><button id="new">新会话</button></nav></header><main id="messages"></main><section id="approvals"></section><footer><div id="connection"></div><div id="attachments"></div><form id="composer"><textarea id="prompt" rows="2"></textarea><div class="actions"><button id="attach" type="button">＋</button><button id="model" type="button">默认模型</button><span id="status"></span><button id="stop" type="button" hidden>■</button><button id="send">↑</button></div></form><div class="hint">project · Enter 发送</div></footer>`);
 await page.evaluate(()=>{window.sent=[];window.acquireVsCodeApi=()=>({postMessage:message=>window.sent.push(message)});});
 await page.addScriptTag({content:await readFile('dist/chat.js','utf8')});
 const state={type:'state',draft:'',busy:false,model:'默认模型',messages:[],attachments:[],approvals:[]};
 const update=async change=>{Object.assign(state,change);await page.evaluate(data=>window.dispatchEvent(new MessageEvent('message',{data})),state);};
 await update({});assert.equal(await page.locator('.empty').count(),1);
 assert.equal(await page.locator('header #reconnect').count(),0);
 await update({connection:'已连接',reconnectNeeded:false});assert.equal(await page.locator('#reconnect').isVisible(),false);
 for(const connection of ['连接已断开','连接失败，可重试','请求超时，请重新连接']) {
  await update({connection,reconnectNeeded:true});
  assert.equal(await page.locator('footer #reconnect').isVisible(),true);
  const recovery=await page.locator('#reconnect').boundingBox();const composer=await page.locator('#composer').boundingBox();assert.ok(recovery.y+recovery.height<composer.y);
 }
 await page.locator('#reconnect').click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='reconnect')));
 await update({connection:'正在连接',reconnectNeeded:true,transition:true});assert.equal(await page.locator('#reconnect').isEnabled(),false);
 await update({connection:'已连接',reconnectNeeded:false,transition:false,phase:'状态待确认，请重连'});assert.equal(await page.locator('#reconnect').isVisible(),true);
 await update({phase:'就绪'});assert.equal(await page.locator('#reconnect').isVisible(),false);
 assert.equal(await page.locator('#send').isEnabled(),false);
 await page.locator('#prompt').fill('/');assert.equal(await page.locator('#slash-menu').isVisible(),true);
 assert.ok(await page.locator('.slash-option').count()>8);
 await page.locator('#prompt').fill('/mode');assert.match(await page.locator('.slash-option').first().textContent(),/^\/mode/);
 await page.locator('#prompt').press('Enter');assert.equal(await page.locator('#prompt').inputValue(),'/mode ');
 const slashReply=async(command,options)=>{const request=await page.evaluate(command=>window.sent.filter(message=>message.type==='slashOptions'&&message.command===command).at(-1),command);await page.evaluate(data=>window.dispatchEvent(new MessageEvent('message',{data})),{type:'slashOptions',command,requestId:request.requestId,options});};
 await slashReply('mode',[{id:'dev',label:'Standard',description:'上下文窗口 272,000 tokens'},{id:'max',label:'Max',description:'上下文窗口 800,000 tokens'}]);
 assert.equal(await page.locator('.slash-option').count(),2);
 await page.locator('#prompt').press('ArrowDown');await update({connection:'已连接'});assert.match(await page.locator('.slash-option[aria-selected=true]').textContent(),/Max/);await page.locator('#prompt').press('Enter');
 assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='slashExecute'&&message.command==='mode'&&message.option==='max')));
 assert.equal(await page.locator('#prompt').inputValue(),'');assert.equal(await page.locator('#slash-menu').isVisible(),false);
 await page.locator('#prompt').fill('/model ');await slashReply('model',[{id:'alpha',label:'Alpha'},{id:'beta',label:'Beta'}]);
 await page.locator('#prompt').fill('/model bet');assert.equal(await page.locator('.slash-option').count(),1);assert.match(await page.locator('.slash-option').textContent(),/Beta/);
 await page.locator('#prompt').press('Escape');assert.equal(await page.locator('#slash-menu').isVisible(),false);
 await page.locator('#prompt').fill('/permissions ');await slashReply('permissions',[{id:'read-only',label:'只读',description:'只读取文件'},{id:'workspace',label:'项目内编辑'}]);
 await page.locator('.slash-option').first().click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='slashExecute'&&message.command==='permissions'&&message.option==='read-only')));
 await page.locator('#prompt').fill('/unknown');assert.equal(await page.locator('.slash-option').count(),0);const sendsBefore=await page.evaluate(()=>window.sent.filter(message=>message.type==='send').length);await page.locator('#prompt').press('Enter');assert.equal(await page.evaluate(()=>window.sent.filter(message=>message.type==='send').length),sendsBefore);
 await page.locator('#prompt').fill('/model ');await slashReply('model',[{id:'alpha',label:'Alpha',description:'示例模型'}]);
 for(const width of [280,380,640]) {await page.setViewportSize({width,height:800});const popup=await page.locator('#slash-menu').boundingBox();const composer=await page.locator('#composer').boundingBox();assert.ok(popup.y+popup.height<composer.y&&popup.x>=0&&popup.x+popup.width<=width);}
 await page.setViewportSize({width:380,height:800});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert.equal(await page.locator('header').count(),1);assert.ok(await page.evaluate(()=>document.documentElement.scrollHeight<=innerHeight));await page.screenshot({path:'docs/slash-commands-preview.png'});await page.locator('#prompt').press('Escape');
 await page.locator('#prompt').fill('   '); assert.equal(await page.locator('#send').isEnabled(),false);
 await page.locator('#prompt').fill('测试'); assert.equal(await page.locator('#send').isEnabled(),true);
 await page.locator('#prompt').fill('');
 for (const width of [280,380,640]) {
  await page.setViewportSize({width,height:800});
  const composer=await page.locator('#composer').boundingBox();
  const send=await page.locator('#send').boundingBox();
  assert.ok(send.x+send.width<composer.x+composer.width && composer.x+composer.width-send.x-send.width<12 && send.y+send.height<composer.y+composer.height);
  await page.locator('#model').click();
  await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'models',models:[{id:'test-model',label:'测试模型',description:'模型说明',selected:true}]}})));
  const anchor=await page.locator('#model').boundingBox();
  const menu=await page.locator('.model-anchor .model-menu').boundingBox();
  assert.ok(Math.abs(menu.x-anchor.x)<1 && menu.y+menu.height<anchor.y);
  assert.ok(menu.x+menu.width<=width);
  await page.getByRole('menuitemradio',{name:'测试模型'}).click();
  assert.ok(await page.locator('.model-anchor .model-menu').isHidden());
 }
 assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='selectModel'&&message.id==='test-model')));
 await page.setViewportSize({width:380,height:800});
 await page.locator('#prompt').fill('解释项目');await page.locator('#prompt').press('Enter');
 assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='send'&&message.text==='解释项目')));
 await update({transition:true,phase:'准备请求',startedAt:Date.now(),messages:[{id:'pending-user',role:'user',text:'解释项目'}]});
 assert.equal(await page.locator('.process-label').textContent(),'正在启动');assert.equal(await page.locator('.process-group[data-status=inProgress]').count(),1);assert.equal(await page.locator('.process-items').isVisible(),false);
 await update({reset:true,busy:false,transition:false,phase:'发送失败',messages:[{id:'pending-user',role:'user',text:'解释项目',status:'failed'}]});
 assert.equal(await page.locator('article.user.failed').count(),1);assert.equal(await page.locator('.message-status').textContent(),'发送失败 · 内容已恢复到输入框');
 await update({busy:true,transition:false,phase:'执行命令',startedAt:Date.now()-45000,messages:[{id:'u1',role:'user',text:'检查构建错误'},{id:'t1',role:'tool',text:'npm run build',status:'inProgress',detail:'Building…'},{id:'a1',role:'assistant',text:'正在检查构建配置。\n\n```ts\nconst root = workspace;\n```'}],attachments:[{id:'c1',label:'src/index.ts:12'}],approvals:[{id:'p1',title:'命令执行需要授权',detail:'npm run build'}]});
	 const userBox=await page.locator('article.user').boundingBox();const messagesBox=await page.locator('#messages').boundingBox();
	 assert.ok(userBox.width<messagesBox.width*.9);assert.ok(Math.abs(userBox.x+userBox.width-(messagesBox.x+messagesBox.width-6))<2);
 const statusBox=await page.locator('#status').boundingBox();
 const activeComposer=await page.locator('#composer').boundingBox();
 assert.ok(statusBox.y+statusBox.height<=activeComposer.y);
 assert.match(await page.locator('#status').textContent(),/^执行命令 · 4[56]秒$/);
	 await update({phase:'模型负载 92% · 排队中 · 队列第 3 位',startedAt:Date.now()-40000});
	 assert.match(await page.locator('#status').textContent(),/^模型负载 92% · 排队中 · 队列第 3 位 · 4[01]秒$/);
	 await update({phase:'执行命令',startedAt:Date.now()-45000});
 assert.equal(await page.locator('#composer #status').count(),0);
 assert.equal(await page.locator('#send').isDisabled(),false);
 assert.equal(await page.locator('#send').getAttribute('aria-label'),'终止任务');
 assert.equal(await page.locator('#send').textContent(),'■');
 assert.equal(await page.locator('.process-label').textContent(),'调用工具 npm run build');
 assert.notEqual(await page.locator('.process-indicator').evaluate(node=>getComputedStyle(node).animationName),'none');
 assert.equal(await page.locator('.process-group').getAttribute('open'),null);
 assert.equal(await page.locator('.tool-title').isVisible(),false);
 await page.locator('.process-summary').click();await page.locator('.tool-title').click();assert.equal(await page.locator('.detail').isVisible(),true);
 await update({phase:'生成回复',messages:[...state.messages.slice(0,1),{...state.messages[1],detail:'Build complete',status:'completed'},{...state.messages[2],status:'streaming'}]});
 assert.equal(await page.locator('.process-label').textContent(),'生成回复中');assert.equal(await page.locator('.process-group[data-status=inProgress]').count(),1);
 assert.equal(await page.locator('.process-group').getAttribute('open'),'');
 assert.equal(await page.locator('.tool-details').getAttribute('open'),'');
 await update({messages:[state.messages[0],state.messages[1],{id:'thought',role:'tool',text:'思考摘要',detail:'检查依赖关系与编译配置',status:'completed'},{id:'search',role:'tool',text:'搜索配置文件',detail:'找到 tsconfig.json',status:'completed'},state.messages[2]]});
 assert.equal(await page.locator('.process-group').count(),1);assert.match(await page.locator('.process-meta').textContent(),/3 项/);
 assert.equal(await page.locator('.process-group').getAttribute('open'),'');
 await page.locator('.process-summary').click();assert.equal(await page.locator('.tool-title').first().isVisible(),false);
 await update({messages:state.messages.map(message=>message.id==='thought'?{...message,detail:'新的思考摘要'}:message)});
 assert.equal(await page.locator('.process-group').getAttribute('open'),null);
 await update({messages:state.messages.map(message=>message.id==='thought'?{...message,status:'inProgress',processKind:'reasoning'}:message)});
 assert.equal(await page.locator('.process-label').textContent(),'思考中');
 await update({messages:state.messages.map(message=>message.id==='search'?{...message,status:'inProgress',toolName:'搜索',processKind:'webSearch'}:message)});
 assert.equal(await page.locator('.process-label').textContent(),'调用工具 搜索');
 await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await page.locator('.process-indicator').evaluate(node=>getComputedStyle(node).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});
 await update({busy:false,messages:state.messages.map(message=>message.role==='tool'?{...message,status:'completed'}:message)});
 assert.equal(await page.locator('.process-label').textContent(),'思考与工具调用');assert.equal(await page.locator('.process-indicator').isVisible(),false);
 await update({reset:true,busy:false,messages:[{id:'reasoning-user',role:'user',text:'分析问题'},{id:'empty-reasoning',role:'tool',text:'思考摘要',status:'completed',processKind:'reasoning',reasoningHasSummary:false}]});
 await page.locator('.process-summary').click();assert.equal(await page.locator('.tool-static').textContent(),'思考 · 已完成');assert.equal(await page.locator('.tool-details').count(),0);
 await update({messages:[state.messages[0],{...state.messages[1],detail:'可展示的思考摘要',reasoningHasSummary:true}]});
 assert.equal(await page.locator('.tool-static').count(),0);assert.equal(await page.locator('.tool-details').count(),1);await page.locator('.tool-title').click();assert.equal(await page.locator('.detail').textContent(),'可展示的思考摘要');
 await update({reset:true,busy:true,phase:'模型处理中',messages:[{id:'multi-user',role:'user',text:'继续处理'},{id:'old-plan',role:'tool',text:'执行计划',detail:'○ 修复问题',status:'inProgress',processKind:'plan',toolName:'计划'},{id:'middle-reply',role:'assistant',text:'开始处理。'},{id:'latest-thought',role:'tool',text:'思考摘要',detail:'检查最新状态',status:'inProgress',processKind:'reasoning'}]});
 assert.equal(await page.locator('.process-group').count(),2);assert.equal(await page.locator('.process-group[data-status=inProgress]').count(),1);
 assert.equal(await page.locator('.process-group').first().locator('.process-indicator').isVisible(),false);assert.equal(await page.locator('.process-group').last().locator('.process-indicator').isVisible(),true);assert.equal(await page.locator('.process-group').last().locator('.process-label').textContent(),'思考中');
 await update({messages:state.messages.map(message=>message.id==='latest-thought'?{...message,status:'completed'}:message)});assert.equal(await page.locator('.process-group[data-status=inProgress]').count(),1);assert.equal(await page.locator('.process-group').first().locator('.process-indicator').isVisible(),false);assert.equal(await page.locator('.process-group').last().locator('.process-label').textContent(),'模型处理中');
 await update({busy:false});assert.equal(await page.locator('.process-group[data-status=inProgress]').count(),0);
 await update({reset:true,busy:true,activeTurnId:'new-turn',phase:'模型处理中',messages:[{id:'old-user',role:'user',text:'旧任务'},{id:'old-tool',turnId:'old-turn',role:'tool',text:'旧工具',status:'inProgress'},{id:'old-reply',role:'assistant',text:'旧任务仍有迟到状态'},{id:'new-user',role:'user',text:'新任务'},{id:'new-tool',turnId:'new-turn',role:'tool',text:'新任务步骤',status:'completed'}]});
 assert.equal(await page.locator('.process-group').count(),2);assert.equal(await page.locator('.process-group').first().locator('.process-indicator').isVisible(),false);assert.equal(await page.locator('.process-group').last().locator('.process-indicator').isVisible(),true);
 await page.getByRole('button',{name:'允许一次'}).click();
 assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='permission'&&message.decision==='accept')));
 await update({busy:true,phase:'模型处理中'});
 await page.locator('#send').click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='stop')));
 await update({busy:false,approvals:[]});
 await mkdir('docs',{recursive:true});await page.screenshot({path:'docs/chat-preview.png'});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
 const composerBox=await page.locator('#composer').boundingBox();
 const sendBox=await page.locator('#send').boundingBox();
 assert.ok(sendBox.x+sendBox.width<=composerBox.x+composerBox.width && composerBox.x+composerBox.width-sendBox.x-sendBox.width<12);
 assert.equal(await page.locator('#send').textContent(),'↑');
 assert.equal(await page.locator('#send').getAttribute('aria-label'),'发送');
 assert.ok(sendBox.y>composerBox.y+composerBox.height/2 && sendBox.y+sendBox.height<=composerBox.y+composerBox.height);
 await page.locator('#model').click();
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'models',models:[{id:'model-one',label:'测试模型',description:'test',selected:true},{id:'model-two',label:'另一个模型',description:'test',selected:false}]}})));
 for (const width of [380,280]) {
  await page.setViewportSize({width,height:800});
  const menuBox=await page.locator('.model-anchor .model-menu').boundingBox();const buttonBox=await page.locator('#model').boundingBox();
  assert.ok(menuBox.y+menuBox.height<=buttonBox.y);
  assert.ok(menuBox.x>=0 && menuBox.x+menuBox.width<=width);
 }
 await page.screenshot({path:'docs/model-menu-preview.png'});
 await page.getByRole('menuitemradio',{name:'另一个模型'}).click();
 assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='selectModel'&&message.id==='model-two')));
 assert.equal(await page.locator('.model-anchor .model-menu').isVisible(),false);
 await page.locator('#model').click();await page.locator('#model').press('Escape');
 assert.equal(await page.locator('.model-anchor .model-menu').isVisible(),false);
 await page.locator('#model').click();await page.locator('.conversation-title').click();
 assert.equal(await page.locator('.model-anchor .model-menu').isVisible(),false);
 await page.setViewportSize({width:380,height:800});
 await update({reset:true,busy:true,messages:[{id:'stream-reply',role:'assistant',text:'已到达的第一段',status:'streaming'}]});
 await page.waitForFunction(()=>document.querySelector('article .content')?.textContent.trim()==='已到达的第一段');
 assert.equal(await page.locator('article.streaming').count(),1);
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'state',reset:false,busy:true,draft:'',messages:[{id:'stream-reply',role:'assistant',text:'已到达的第一段和第二段',status:'streaming'}],removed:[],attachments:[],approvals:[],model:'默认模型'}})));
 await page.waitForFunction(()=>document.querySelector('article .content')?.textContent.trim()==='已到达的第一段和第二段');
 await page.evaluate(()=>{window.streamingTextNode=document.querySelector('article .content').firstChild;window.dispatchEvent(new MessageEvent('message',{data:{type:'stream',id:'stream-reply',delta:'第三段'}}));});
 await page.waitForFunction(()=>document.querySelector('article .content')?.textContent.trim().endsWith('第三段'));
 assert.ok(await page.evaluate(()=>window.streamingTextNode===document.querySelector('article .content').firstChild));
 await update({busy:false,messages:[{id:'stream-reply',role:'assistant',text:'已到达的第一段和第二段第三段',status:'completed'}]});
 await page.waitForFunction(()=>!document.querySelector('article.streaming'));
 assert.equal((await page.locator('article .content').textContent()).trim(),'已到达的第一段和第二段第三段');
 await page.locator('#prompt').fill('不能被旧状态覆盖');
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'state',reset:false,messages:[],removed:[],busy:false,draft:'旧草稿',draftRevision:0,attachments:[],approvals:[],model:'默认模型'}})));
 assert.equal(await page.locator('#prompt').inputValue(),'不能被旧状态覆盖');
 await update({reset:true,messages:Array.from({length:350},(_,i)=>({id:'long-'+i,role:'assistant',text:'消息 '+i}))});
 assert.equal(await page.locator('article').count(),200);
 await page.getByRole('button',{name:'查看更早的消息'}).click();
 assert.equal(await page.locator('article').count(),200);
 assert.equal((await page.locator('article .content').first().textContent()).trim(),'消息 0');
 await page.getByRole('button',{name:'回到最新'}).click();
 assert.equal(await page.locator('article').count(),200);
 const partial = '**实时标题**\n\n- 项目一\n\n```ts\nconst n = 1;\n';
 await update({reset:true,busy:true,messages:[{id:'md-live',role:'assistant',text:partial,status:'streaming'}]});
 await page.waitForFunction(()=>document.querySelector('article pre code')?.textContent.includes('const n = 1;'));
 assert.equal(await page.locator('article strong').textContent(),'实时标题');
 assert.equal(await page.locator('article li').textContent(),'项目一');
 assert.equal(await page.locator('#send').getAttribute('aria-label'),'终止任务');
 await page.evaluate(()=>{window.stableParagraph=document.querySelector('article p');window.stableCode=document.querySelector('article pre code');});
 const tail = 'console.log(n);\n```\n\n完成。';
 await page.evaluate(delta=>window.dispatchEvent(new MessageEvent('message',{data:{type:'stream',id:'md-live',delta}})),tail);
 await page.waitForFunction(()=>document.querySelector('article pre code')?.textContent.includes('console.log(n);')&&document.querySelector('article .content')?.textContent.includes('完成。'));
 assert.ok(await page.evaluate(()=>window.stableParagraph===document.querySelector('article p')&&window.stableCode===document.querySelector('article pre code')));
 await page.screenshot({path:'docs/live-markdown-preview.png'});
 await update({busy:false,messages:[{id:'md-live',role:'assistant',text:partial+tail,status:'completed'}]});
 await page.waitForFunction(()=>!document.querySelector('article.streaming'));
 assert.ok(await page.evaluate(()=>window.stableParagraph===document.querySelector('article p')&&window.stableCode===document.querySelector('article pre code')));
 await update({page:'sessions',busy:false,historyLoading:false,historyError:'',project:'当前项目',sessions:[{id:'one',title:'修复测试',preview:'检查构建',updatedAt:100,model:'test-model'}],hasMoreSessions:true});
 assert.equal(await page.locator('#composer').isVisible(),false);
 assert.equal(await page.locator('#messages').isVisible(),false);
 assert.equal(await page.locator('.session-card').count(),1);
 await page.locator('.session-card').click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='openSession'&&message.id==='one')));
 await page.getByRole('button',{name:'加载更多',exact:true}).click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='moreSessions')));
 await page.screenshot({path:'docs/session-home-preview.png'});
 await update({page:'chat'});assert.equal(await page.locator('#composer').isVisible(),true);
 await page.locator('#back').click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='back')));
 await update({page:'chat',viewKey:'conversation-a',draftRevision:10,draft:'会话 A 草稿',busy:true,reset:true,messages:[{id:'same-item',role:'assistant',text:'A 正在运行'}]});
 assert.equal(await page.locator('#new').isEnabled(),true); assert.equal(await page.locator('#back').isEnabled(),true);
 const backBox = await page.locator('#back').boundingBox(); assert.ok(backBox.x < 30 && backBox.y < 30);
 await update({page:'sessions',sessions:[{id:'a',title:'会话 A',updatedAt:100,status:'等待授权'},{id:'b',title:'会话 B',updatedAt:101,status:'执行中'}]});
 assert.equal(await page.locator('.session-card:disabled').count(),0);
 await update({page:'chat',viewKey:'conversation-b',draftRevision:0,draft:'会话 B 草稿',busy:true,reset:true,messages:[{id:'same-item',role:'assistant',text:'B 正在运行'}]});
 assert.equal(await page.locator('#prompt').inputValue(),'会话 B 草稿');
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'stream',viewKey:'conversation-a',id:'same-item',delta:'不应显示在 B'}})));
 assert.equal((await page.locator('article .content').textContent()).trim(),'B 正在运行');
 await page.screenshot({path:'docs/concurrent-session-preview.png'});
 await update({page:'chat',busy:false,reasoning:'medium',reasoningSupported:true});
 await page.locator('#reasoning').click();
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'reasoningLevels',options:[{id:'medium',description:'平衡',selected:true},{id:'high',description:'深入',selected:false}]}})));
 for(const width of [280,380,640]) {await page.setViewportSize({width,height:800});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const button=await page.locator('#reasoning').boundingBox();const menu=await page.locator('.reasoning-menu').boundingBox();assert.ok(menu.y+menu.height<button.y&&menu.x>=0&&menu.x+menu.width<=width,JSON.stringify({width,button,menu}));}
 await page.getByRole('menuitemradio',{name:'High',exact:true}).click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='selectReasoning'&&message.effort==='high')));
 await update({reasoning:'high'});assert.equal(await page.locator('#reasoning').textContent(),'High⌄');
 await page.locator('#reasoning').click();await page.locator('#reasoning').press('Escape');assert.equal(await page.locator('.reasoning-menu').isVisible(),false);
 await update({reasoningSupported:false});assert.equal(await page.locator('#reasoning').isVisible(),false);assert.equal(await page.locator('.reasoning-menu').isVisible(),false);
 await page.setViewportSize({width:380,height:800});await update({reasoningSupported:true,reasoning:'high'});await page.locator('#reasoning').click();
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'reasoningLevels',options:[{id:'low',selected:false},{id:'medium',selected:false},{id:'high',selected:true}]}})));
 await page.screenshot({path:'docs/reasoning-menu-preview.png'});await page.locator('#reasoning').press('Escape');
 await update({page:'chat',modeSupported:true,modelMode:'sol__dev',modeLabel:'Standard'});await page.locator('#mode').click();
 assert.equal(await page.locator('#tier').count(),0);
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'modelModes',options:[{id:'sol__dev',name:'Standard',description:'272,000 tokens',selected:true},{id:'sol__max',name:'Max',description:'800,000 tokens',selected:false}]}})));
 for(const width of [280,380,640]){await page.setViewportSize({width,height:800});await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const button=await page.locator('#mode').boundingBox();const menu=await page.locator('.mode-menu').boundingBox();assert.ok(menu.y+menu.height<button.y&&menu.x>=0&&menu.x+menu.width<=width);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.getByRole('menuitemradio',{name:'Max'}).click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='selectMode'&&message.mode==='sol__max')));
 await update({modelMode:'sol__max',modeLabel:'Max'});assert.equal(await page.locator('#mode').textContent(),'Max⌄');
 await update({modeSupported:true,modelMode:'single__dev',modeLabel:'Standard'});await page.locator('#mode').click();
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'modelModes',options:[{id:'single__dev',name:'Standard',description:'上下文窗口 128,000 tokens',selected:true}]}})));
 assert.equal(await page.locator('.mode-menu').isVisible(),true);assert.match(await page.locator('.mode-menu').textContent(),/128,000 tokens/);
 await update({modeSupported:false,modeLabel:'Standard'});assert.equal(await page.locator('#mode').isVisible(),false);assert.equal(await page.locator('.mode-menu').isVisible(),false);
 await page.setViewportSize({width:380,height:800});await update({modeSupported:true,modelMode:'sol__max',modeLabel:'Max',model:'GPT-5.6-Sol'});await page.locator('#mode').click();
 await page.evaluate(()=>window.dispatchEvent(new MessageEvent('message',{data:{type:'modelModes',options:[{id:'sol__dev',name:'Standard',description:'272,000 tokens',selected:false},{id:'sol__max',name:'Max',description:'800,000 tokens',selected:true}]}})));
 await page.screenshot({path:'docs/model-mode-preview.png'});await page.locator('#mode').press('Escape');assert.equal(await page.locator('.mode-menu').isVisible(),false);
 await update({page:'chat',modeSupported:true,permissionMode:'default'});
 for(const width of [280,380,640]) {
  await page.setViewportSize({width,height:800});
  const mode=await page.locator('#mode').boundingBox();const permission=await page.locator('#permissions').boundingBox();const composer=await page.locator('#composer').boundingBox();
  const model=await page.locator('#model').boundingBox();const reasoning=await page.locator('#reasoning').boundingBox();
  const send=await page.locator('#send').boundingBox();const attach=await page.locator('#attach').boundingBox();
  assert.ok(permission.x+permission.width<=send.x && send.x-permission.x-permission.width<8);
  assert.ok(Math.abs((permission.y+permission.height/2)-(send.y+send.height/2))<2);
  assert.ok(attach.x-composer.x<12 && attach.x+attach.width<=model.x && model.x-attach.x-attach.width<8);
  assert.ok(Math.abs((attach.y+attach.height/2)-(model.y+model.height/2))<2);
  assert.ok(composer.x+composer.width-send.x-send.width<12);
  for(const box of [attach,model,mode,reasoning,permission].filter(Boolean)) assert.ok(Math.abs((box.y+box.height/2)-(send.y+send.height/2))<2);
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  assert.ok(mode.x>=model.x+model.width && mode.x-model.x-model.width<8);
  if(reasoning) assert.ok(reasoning.x>=mode.x+mode.width && reasoning.x-mode.x-mode.width<8);
  await page.locator('#permissions').click();await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const menu=await page.locator('.permissions-menu').boundingBox();assert.ok(menu.y+menu.height<permission.y&&menu.x>=0&&menu.x+menu.width<=width);
  await page.locator('#permissions').press('Escape');assert.equal(await page.locator('.permissions-menu').isVisible(),false);
 }
 await page.locator('#permissions').click();await page.getByRole('menuitemradio',{name:'只读',exact:false}).click();assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='selectPermissions'&&message.mode==='read-only')));
 await update({permissionMode:'read-only'});assert.equal(await page.locator('#permissions').textContent(),'只读⌄');
 await page.locator('#permissions').click();assert.equal(await page.locator('.permissions-menu').isVisible(),true);
 await update({busy:true,transition:false});
 assert.equal(await page.locator('#permissions').isDisabled(),true);assert.equal(await page.locator('.permissions-menu').isVisible(),false);
 assert.equal(await page.locator('.permissions-anchor').getAttribute('title'),'当前任务已按启动时权限运行，任务结束后可修改。');
 await page.locator('#prompt').fill('/permissions');assert.equal(await page.locator('.slash-option').isDisabled(),true);
 await page.locator('#prompt').fill('');await update({busy:false});
 assert.equal(await page.locator('#permissions').isEnabled(),true);assert.match(await page.locator('#permissions').getAttribute('title'),/下一个任务生效/);
 await page.setViewportSize({width:380,height:800});await page.locator('#permissions').click();await page.screenshot({path:'docs/permissions-preview.png'});await page.locator('#permissions').press('Escape');
 await update({tokenUsage:{session:12345}});
 assert.equal(await page.locator('.usage-range').count(),0);
 assert.equal(await page.locator('.usage-label').count(),0);
 assert.match(await page.locator('.usage-value').textContent(),/12.35K tokens/);
 assert.equal(await page.locator('.usage-value').getAttribute('title'),'12,345 tokens');
 for(const [tokens,formatted] of [[999,'999'],[1000,'1K'],[1000000,'1M'],[1000000000,'1B'],[1000000000000,'1T'],[999999,'1M']]) {
  await update({tokenUsage:{session:tokens}});assert.equal(await page.locator('.usage-value').textContent(),formatted+' tokens');
 }
 await update({tokenUsage:{session:12500}});
 assert.equal(await page.locator('.usage-value').textContent(),'12.5K tokens');
 await update({viewKey:'usage-other-session',tokenUsage:{session:20}});
 assert.equal(await page.locator('.usage-value').textContent(),'20 tokens');
 await update({tokenUsage:{session:null}});
 assert.equal(await page.locator('.usage-value').textContent(),'— tokens');
 await update({tokenUsage:{session:12345}});
 for(const width of [280,380,640]) {await page.setViewportSize({width,height:800});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.setViewportSize({width:380,height:800});await page.screenshot({path:'docs/token-usage-preview.png'});
 await update({page:'sessions',authRequired:true,loginPending:false,loginError:''});
 assert.equal(await page.locator('#session-home').isVisible(),false); assert.equal(await page.locator('#composer').isVisible(),false);
 await page.getByRole('button',{name:'去登录',exact:true}).click(); assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='login')));
 await update({authRequired:true,loginPending:true}); assert.equal(await page.getByRole('button',{name:'查看登录终端'}).isVisible(),true);
 await page.getByRole('button',{name:'我已登录，重新检测'}).click(); assert.ok(await page.evaluate(()=>window.sent.some(message=>message.type==='checkLogin')));
 await page.screenshot({path:'docs/login-preview.png'});
 await update({authRequired:false,loginPending:false}); assert.equal(await page.locator('#auth-panel').isVisible(),false); assert.equal(await page.locator('#session-home').isVisible(),true);
 await update({page:'sessions',authRequired:false,currentSession:'a',sessions:[{id:'a',title:'修复流式输出的渲染体验',preview:'检查渲染和滚动行为',updatedAt:Math.floor(Date.now()/1000),status:'等待授权',model:'TRAE Model'},{id:'b',title:'补齐接口测试',updatedAt:Math.floor(Date.now()/1000)-120,status:'执行命令',model:'TRAE Model'},{id:'c',title:'整理项目文档',updatedAt:Math.floor(Date.now()/1000)-86400,model:'TRAE Model'}]});
 assert.equal(await page.locator('.session-group').count(),2); assert.equal(await page.locator('.session-badge').count(),2);
 await page.locator('[data-session-id="a"]').focus(); await update({sessions:state.sessions.map(item=>({...item,updatedAt:item.updatedAt+1}))});
 assert.equal(await page.evaluate(()=>document.activeElement.dataset.sessionId),'a');
 await page.screenshot({path:'docs/session-list-refined-dark.png'});
 await page.evaluate(()=>{const colors={'foreground':'#333333','sideBar-background':'#f6f6f6','descriptionForeground':'#666666','panel-border':'#d6d6d6','editorWidget-background':'#ffffff','input-background':'#ffffff','input-foreground':'#333333','textCodeBlock-background':'#f0f0f0','badge-background':'#e7e7e7','badge-foreground':'#333333','list-inactiveSelectionBackground':'#e8e8e8','list-hoverBackground':'#eeeeee','textLink-foreground':'#006ab1','editorWarning-foreground':'#986500','toolbar-hoverBackground':'#e4e4e4','scrollbarSlider-background':'#bbbbbb'};for(const [key,value]of Object.entries(colors)) document.documentElement.style.setProperty('--vscode-'+key,value);});
 for(const width of [280,380,640]) {await page.setViewportSize({width,height:800});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}
 await page.setViewportSize({width:380,height:800}); await page.screenshot({path:'docs/session-list-refined-light.png'});
 await update({page:'chat',conversationTitle:'修复流式输出的渲染体验',busy:false,draft:'',messages:[{id:'light',role:'assistant',text:'已完成调整。\n\n```ts\nconst ready = true;\n```'}],reset:true});
 assert.equal(await page.locator('.conversation-title').textContent(),'修复流式输出的渲染体验');
 await page.screenshot({path:'docs/chat-refined-light.png'});
 console.log('Session homepage, click-through, live Markdown and composer interactions verified.');
} finally { await browser.close(); }
