const assert = require('node:assert/strict');
const vscode = require('vscode');
const path = require('node:path');
const fs = require('node:fs/promises');
exports.run = async function () {
  const { Sidebar } = require(path.join(process.env.TRAE_TEST_ROOT, 'dist/extension.js'));
  const data = new Map();
  const subscriptions = [];
  const context = { extensionUri: vscode.Uri.file(process.env.TRAE_TEST_ROOT), subscriptions, workspaceState: { get: (key, fallback) => data.get(key) ?? fallback, update: async (key, value) => data.set(key, value) } };
  const previousUniqueThreads = process.env.TRAE_TEST_UNIQUE_THREADS; process.env.TRAE_TEST_UNIQUE_THREADS = '1';
  const sidebar = new Sidebar(context); sidebar.page = 'chat'; sidebar.readLoginStatus = async () => true;
  const panel = vscode.window.createWebviewPanel('trae-test', 'TRAE integration test', vscode.ViewColumn.One, { enableScripts: true });
  sidebar.resolveWebviewView({ webview: panel.webview, onDidDispose: panel.onDidDispose, show: () => panel.reveal() });
  try {
    const config = vscode.workspace.getConfiguration('traecli');
    await config.update('executable', process.env.TRAE_TEST_NODE, vscode.ConfigurationTarget.Global);
    await config.update('arguments', [path.join(process.env.TRAE_TEST_ROOT, 'tests/mock-server.cjs')], vscode.ConfigurationTarget.Global);
    const sample = vscode.Uri.joinPath(vscode.workspace.workspaceFolders[0].uri, 'sample.txt');
    await fs.writeFile(sample.fsPath, 'after\n');
    await sidebar.addFile(sample);
    assert.equal(sidebar.attachments.length, 1);
    await sidebar.send('test host flow');
    assert.ok(sidebar.threadId);
    for (let i = 0; i < 30 && !sidebar.approvals.size; i++) await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(sidebar.approvals.size, 1);
    const firstThread=sidebar.threadId;
    await sidebar.history(); assert.equal(sidebar.busy,true);
    await sidebar.restart(); const second=sidebar.current;
    await second.send('parallel host task');
    for (let i=0;i<30&&!second.approvals.size;i++) await new Promise(resolve=>setTimeout(resolve,50));
    assert.notEqual(firstThread,second.threadId); assert.equal(sidebar.busy,true); assert.equal(second.busy,true);
    assert.equal(sidebar.approvals.size,1); assert.equal(second.approvals.size,1);
    await second.cancel();
    for(let i=0;i<30&&second.busy;i++) await new Promise(resolve=>setTimeout(resolve,50));
    assert.equal(second.busy,false); assert.equal(sidebar.busy,true); assert.equal(sidebar.approvals.size,1);
    await sidebar.openSession(firstThread); assert.equal(sidebar.current,sidebar);
    await sidebar.cancel();
    for (let i = 0; i < 30 && sidebar.busy; i++) await new Promise(resolve => setTimeout(resolve, 50));
    assert.equal(sidebar.busy, false);
    assert.equal(sidebar.approvals.size, 0);
    const { createPatch } = require('diff');
    sidebar.messages.push({ id: 'file-test', role: 'tool', text: 'file change', paths: [sample.fsPath], changes: [{ path: sample.fsPath, diff: createPatch('sample.txt', 'before\n', 'after\n') }] });
    await sidebar.reviewFile('file-test', sample.fsPath);
    await new Promise(resolve => setTimeout(resolve, 100));
    assert.ok(vscode.window.tabGroups.all.flatMap(group => group.tabs).some(tab => tab.input instanceof vscode.TabInputTextDiff));
    const before = [...sidebar.virtualDocuments.values()];
    assert.ok(before.includes('before\n'));assert.ok(before.includes('after\n'));
    console.log('PASS: actual VS Code host kept two CLI conversations running, isolated approvals and stop, and opened native diff.');
  } finally { if(previousUniqueThreads===undefined) delete process.env.TRAE_TEST_UNIQUE_THREADS; else process.env.TRAE_TEST_UNIQUE_THREADS=previousUniqueThreads; sidebar.dispose(); panel.dispose(); for (const subscription of subscriptions) subscription.dispose(); }
};
